config/routes.rb
Rails.application.routes.draw do
  

  resources :users, :only => [:new, :create]
  resources :restaurants do
    resources :reservations, :only => [:new, :create]
    end

  resources :sessions, :only => [:new, :create, :destroy]

  resources :reservations, :only => [:index, :show, :edit, :update, :destroy]
 

  root 'restaurants#index'

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  validates :name, :description, :location, :presence => true
  validates :max_occupancy, :numericality => {:only_integer => true}

  CUISINE_TYPES = ["Mexican","French","Japanese", "American","Korean", "Italian"]
  has_many :reservations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def ensure_logged_in
    unless current_user
      flash[:alert] = "Please log in"
      redirect_to new_session_path
    end
  end

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_filter :ensure_logged_in, :only => [:show, :index]

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)

      if @restaurant.save
          redirect_to restaurants_path
      else
        render :new
      end
  end

  def update
    @restaurant = Resturant.find(params[:id])

      if restaurant.update_attributes(resturant_params)
        redirect_to restaurant_path(@restaurant)
      else
        render :edit
      end
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to restaurants_path
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def index
    @restaurants = Restaurant.all
  end


  private
  def restaurant_params
    params.require(:restaurant).permit(:name, :description, :cuisine, :user_id, :location, :max_occupancy)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Seatyourself</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if flash[:notice] %>
    <p id ="notice"> <%= flash[:notice] %></p>
  <%end%>

  <% if flash[:alert] %>
    <p id="alert"><%= flash[:alert] %></p>
  <%end%>

  <p class="userinfo">
      <% if current_user %>
        Signed in as <%= current_user.first_name %>. <%= link_to "Log out", session_path("current"), :method => :delete %>
      <% else %>
        <%= link_to "Log in", new_session_path %> or <%= link_to "Sign up", new_user_path %>
      <% end %>
    </p>


<%= yield %>

</body>
</html>

app/views/restaurants/edit.html.erb
<h1>Restaurants#edit</h1>
<%= render 'form' %>

app/views/restaurants/new.html.erb
<h1>Restaurants#new</h1>
<%=render 'form' %>